ALTER TABLE users ADD COLUMN email_opt_in INTEGER NOT NULL DEFAULT 1;
ALTER TABLE users ADD COLUMN admin_note TEXT;
ALTER TABLE users ADD COLUMN login_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN updated_at TEXT;
