/** Liên Quân heroes — static seed (no Garena API). Vietnamese tips. */
export const HEROES = [
  {
    id: 'florentino',
    name: 'Florentino',
    aliases: ['flo', 'kiếm sĩ'],
    lane: 'top',
    tier: 'S+',
    weakAgainst: ['aleister', 'arum', 'veres'],
    tip: 'Gặp Florentino: đừng trade trước level 2 — skill 1 của hắn quá mạnh early.',
  },
  {
    id: 'nakroth',
    name: 'Nakroth',
    aliases: ['nak'],
    lane: 'jungle',
    tier: 'S+',
    weakAgainst: ['taara', 'xeniel', 'grakk'],
    tip: 'Nakroth gank sớm: giữ bụi, đợi skill 2 rồi mới nhảy — đừng bay lung tung.',
  },
  {
    id: 'murad',
    name: 'Murad',
    aliases: [],
    lane: 'jungle',
    tier: 'S',
    weakAgainst: ['airi', 'zuka', 'taara'],
    tip: 'Murad cần stack trước khi all-in. Đừng 1v1 khi chưa đủ dấu ấn.',
  },
  {
    id: 'raz',
    name: 'Raz',
    aliases: [],
    lane: 'mid',
    tier: 'S+',
    weakAgainst: ['krixi', 'natalya', 'gildur'],
    tip: 'Raz poke bằng skill 1 — giữ khoảng cách, đừng để bị dồn sát thương gần.',
  },
  {
    id: 'violet',
    name: 'Violet',
    aliases: ['vio'],
    lane: 'adc',
    tier: 'S',
    weakAgainst: ['yorn', 'elsu', 'wiro'],
    tip: 'Violet kiting: luôn giữ khoảng cách sau mỗi phát bắn, đừng đứng im.',
  },
  {
    id: 'airi',
    name: 'Airi',
    aliases: ['airy'],
    lane: 'jungle',
    tier: 'A',
    weakAgainst: ['nakroth', 'zill', 'veres'],
    tip: 'Airi combo nhanh — luyện skill 2 → 1 → ult cho mượt trước khi leo rank.',
  },
  {
    id: 'veres',
    name: 'Veres',
    aliases: [],
    lane: 'top',
    tier: 'S',
    weakAgainst: ['arthur', 'ormarr', 'taara'],
    tip: 'Veres mạnh mid-game. Tránh 1v1 quá sớm nếu đối phương có giáp.',
  },
  {
    id: 'aleister',
    name: 'Aleister',
    aliases: ['ale'],
    lane: 'mid',
    tier: 'A',
    weakAgainst: ['krixi', 'raz', 'natalya'],
    tip: 'Aleister set combat bằng ult — báo team trước khi thả vòng.',
  },
  {
    id: 'arum',
    name: 'Arum',
    aliases: [],
    lane: 'top',
    tier: 'A',
    weakAgainst: ['wiro', 'xeniel', 'ormarr'],
    tip: 'Arum ôm mục tiêu trong bụi — đừng ult lộ khi team chưa sẵn sàng.',
  },
  {
    id: 'taara',
    name: 'Taara',
    aliases: [],
    lane: 'top',
    tier: 'A',
    weakAgainst: ['arthur', 'slimz', 'elsu'],
    tip: 'Taara tank đường — nhường farm cho AD, giữ skill hồi máu cho combat.',
  },
  {
    id: 'xeniel',
    name: 'Xeniel',
    aliases: ['xen'],
    lane: 'sp',
    tier: 'S',
    weakAgainst: ['grakk', 'krizzix', 'annette'],
    tip: 'Xeniel ult cứu đồng đội — đếm CD địch trước khi bay vào.',
  },
  {
    id: 'grakk',
    name: 'Grakk',
    aliases: [],
    lane: 'sp',
    tier: 'A',
    weakAgainst: ['annette', 'krizzix', 'zip'],
    tip: 'Grakk hook trong bụi — một hook trượt là mất tempo, kiên nhẫn.',
  },
  {
    id: 'krixi',
    name: 'Krixi',
    aliases: [],
    lane: 'mid',
    tier: 'A',
    weakAgainst: ['natalya', 'gildur', 'tulen'],
    tip: 'Krixi clear wave nhanh rồi roam — đừng ngồi mid cả trận.',
  },
  {
    id: 'natalya',
    name: 'Natalya',
    aliases: ['nata'],
    lane: 'mid',
    tier: 'S',
    weakAgainst: ['gildur', 'raz', 'zill'],
    tip: 'Natalya cần vị trí an toàn — luôn đứng sau tank khi teamfight.',
  },
  {
    id: 'yorn',
    name: 'Yorn',
    aliases: [],
    lane: 'adc',
    tier: 'A',
    weakAgainst: ['wiro', 'elsu', 'violet'],
    tip: 'Yorn tầm xa: giữ khoảng cách tối đa, đừng chase vào bụi.',
  },
  {
    id: 'elsu',
    name: 'Elsu',
    aliases: [],
    lane: 'adc',
    tier: 'S+',
    weakAgainst: ['wiro', 'murad', 'nakroth'],
    tip: 'Elsu bắn từ xa — một phát miss là nguy hiểm, canh góc map.',
  },
  {
    id: 'wiro',
    name: 'Wiro',
    aliases: [],
    lane: 'top',
    tier: 'A',
    weakAgainst: ['florentino', 'veres', 'arthur'],
    tip: 'Wiro chống AD tốt — build giáp theo meta trận đấu.',
  },
  {
    id: 'arthur',
    name: 'Arthur',
    aliases: [],
    lane: 'top',
    tier: 'B',
    weakAgainst: ['florentino', 'veres', 'murad'],
    tip: 'Arthur ổn định cho người mới — tập engage đúng lúc ult.',
  },
  {
    id: 'zuka',
    name: 'Zuka',
    aliases: [],
    lane: 'jungle',
    tier: 'A',
    weakAgainst: ['nakroth', 'airi', 'zill'],
    tip: 'Zuka bay vào backline — chọn mục tiêu AD/mage trước.',
  },
  {
    id: 'zill',
    name: 'Zill',
    aliases: [],
    lane: 'jungle',
    tier: 'A',
    weakAgainst: ['taara', 'xeniel', 'grakk'],
    tip: 'Zill gank bằng tốc độ — đừng farm quá lâu nếu lane đang thua.',
  },
  {
    id: 'tulen',
    name: 'Tulen',
    aliases: [],
    lane: 'mid',
    tier: 'A',
    weakAgainst: ['raz', 'natalya', 'gildur'],
    tip: 'Tulen burst cao — chờ skill CD rồi mới all-in.',
  },
  {
    id: 'gildur',
    name: 'Gildur',
    aliases: [],
    lane: 'mid',
    tier: 'B',
    weakAgainst: ['krixi', 'elsu', 'yorn'],
    tip: 'Gildur set bằng ult — báo team trước khi đóng tường.',
  },
  {
    id: 'ormarr',
    name: 'Ormarr',
    aliases: [],
    lane: 'sp',
    tier: 'A',
    weakAgainst: ['annette', 'zip', 'krizzix'],
    tip: 'Ormarr engage thẳng — đừng ult khi team còn ở base.',
  },
  {
    id: 'annette',
    name: 'Annette',
    aliases: ['anne'],
    lane: 'sp',
    tier: 'S',
    weakAgainst: ['grakk', 'ormarr', 'zip'],
    tip: 'Annette peel cho AD — ưu tiên cứu carry hơn là chase kill.',
  },
  {
    id: 'krizzix',
    name: 'Krizzix',
    aliases: ['kris'],
    lane: 'sp',
    tier: 'A',
    weakAgainst: ['xeniel', 'annette', 'grakk'],
    tip: 'Krizzix bẫy trong bụi — một set tốt đổi cả trận.',
  },
  {
    id: 'zip',
    name: 'Zip',
    aliases: [],
    lane: 'sp',
    tier: 'B',
    weakAgainst: ['grakk', 'ormarr', 'annette'],
    tip: 'Zip cứu đồng đội bằng bóng — canh timing skill địch.',
  },
  {
    id: 'slimz',
    name: 'Slimz',
    aliases: [],
    lane: 'adc',
    tier: 'B',
    weakAgainst: ['violet', 'yorn', 'elsu'],
    tip: 'Slimz cần farm — tránh fight sớm nếu chưa có đồ.',
  },
  {
    id: 'butterfly',
    name: 'Butterfly',
    aliases: ['bf'],
    lane: 'jungle',
    tier: 'A',
    weakAgainst: ['taara', 'arthur', 'xeniel'],
    tip: 'Butterfly late-game mạnh — sống sót early rồi scale.',
  },
];

export const HERO_BY_ID = Object.fromEntries(HEROES.map((h) => [h.id, h]));

export function getHero(id) {
  return HERO_BY_ID[String(id || '').toLowerCase()] || null;
}

export function resolveCounters(hero) {
  if (!hero?.weakAgainst?.length) return [];
  return hero.weakAgainst.map((id) => getHero(id)).filter(Boolean);
}
