/** Curated sample boasts when DB is empty */
export const KHOE_SEED = [
  {
    id: 'seed-1',
    display_name: 'FloMain_SG',
    caption: 'Florentino quadra — lane đối phương out luôn 🔥 Copy giáo án Bang là ăn ngay.',
    hero_id: 'florentino',
    tiktok_url: '',
    image_url: '/images/lienquan/khoe-flo.svg',
    like_count: 42,
    created_at: '2026-07-09T12:00:00Z',
  },
  {
    id: 'seed-2',
    display_name: 'NakGank',
    caption: 'Nakroth gank 3 lane trong 2 phút. Múa tướng thật — Maris build không phải meme.',
    hero_id: 'nakroth',
    tiktok_url: '',
    image_url: '/images/lienquan/khoe-nak.svg',
    like_count: 28,
    created_at: '2026-07-08T18:00:00Z',
  },
  {
    id: 'seed-3',
    display_name: 'ElsuSniper',
    caption: 'Elsu pentakill từ bụi — clip để khoe group FB. Đối thủ không biết mắt ở đâu 😂',
    hero_id: 'elsu',
    tiktok_url: '',
    image_url: '/images/lienquan/khoe-elsu.svg',
    like_count: 61,
    created_at: '2026-07-07T21:00:00Z',
  },
  {
    id: 'seed-4',
    display_name: 'LiliMidGod',
    caption: 'Liliana solo kill Raz mid 3 lần liên tiếp — đối phương ff15 trong lòng.',
    hero_id: 'liliana',
    tiktok_url: '',
    image_url: '/images/lienquan/khoe-flo.svg',
    like_count: 35,
    created_at: '2026-07-09T08:30:00Z',
  },
  {
    id: 'seed-5',
    display_name: 'ThaneTankVN',
    caption: 'Thane 1v5 giữ nhà — team respawn rồi lật kèo. Tank trâu meta AOG 💪',
    hero_id: 'thane',
    tiktok_url: '',
    image_url: '/images/lienquan/khoe-nak.svg',
    like_count: 19,
    created_at: '2026-07-08T14:00:00Z',
  },
  {
    id: 'seed-6',
    display_name: 'KeeraCarry',
    caption: 'Keera xuyên tường cướp Baron — cả lobby chat "hack?" 🤣',
    hero_id: 'keera',
    tiktok_url: '',
    image_url: '/images/lienquan/khoe-elsu.svg',
    like_count: 47,
    created_at: '2026-07-07T16:45:00Z',
  },
  {
    id: 'seed-7',
    display_name: 'YenaTopLane',
    caption: 'Yena Viên Đao outplay Florentino — BirdLB build đúng bài không sợ trade.',
    hero_id: 'yena',
    tiktok_url: '',
    image_url: '/images/lienquan/khoe-flo.svg',
    like_count: 22,
    created_at: '2026-07-06T20:00:00Z',
  },
  {
    id: 'seed-8',
    display_name: 'HayateADC',
    caption: 'Hayate Chuỗi Phi Tiêu trúng hết — AD không cần support peel khi aim chuẩn.',
    hero_id: 'hayate',
    tiktok_url: '',
    image_url: '/images/lienquan/khoe-nak.svg',
    like_count: 31,
    created_at: '2026-07-06T11:00:00Z',
  },
  {
    id: 'seed-9',
    display_name: 'AoiJungle',
    caption: 'Aoi long trảo teamfight — Gray giáo án đu dây xa quá bất công.',
    hero_id: 'aoi',
    tiktok_url: '',
    image_url: '/images/lienquan/khoe-elsu.svg',
    like_count: 26,
    created_at: '2026-07-05T19:30:00Z',
  },
  {
    id: 'seed-10',
    display_name: 'RazMidVN',
    caption: 'Raz Cú Đấm Chân Không đẩy 3 người vào tường — combo núp bụi classic.',
    hero_id: 'raz',
    tiktok_url: '',
    image_url: '/images/lienquan/khoe-flo.svg',
    like_count: 18,
    created_at: '2026-07-05T09:00:00Z',
  },
  {
    id: 'seed-11',
    display_name: 'VioletLate',
    caption: 'Violet lộn bắn teamfight — 2 phát xóa sạch backline. Late game là của tôi.',
    hero_id: 'violet',
    tiktok_url: '',
    image_url: '/images/lienquan/khoe-nak.svg',
    like_count: 39,
    created_at: '2026-07-04T22:00:00Z',
  },
  {
    id: 'seed-12',
    display_name: 'ZukaDive',
    caption: 'Zuka lao thẳng ADC — Kuga build xuyên giáp không ai cứu kịp.',
    hero_id: 'zuka',
    tiktok_url: '',
    image_url: '/images/lienquan/khoe-elsu.svg',
    like_count: 15,
    created_at: '2026-07-04T15:00:00Z',
  },
  {
    id: 'seed-13',
    display_name: 'OmenSplit',
    caption: 'Omen split push 2 lane — địch chase 4 người còn trụ nhà mất sạch.',
    hero_id: 'omen',
    tiktok_url: '',
    image_url: '/images/lienquan/khoe-flo.svg',
    like_count: 24,
    created_at: '2026-07-03T18:00:00Z',
  },
  {
    id: 'seed-14',
    display_name: 'KrixiCC',
    caption: 'Krixi hất tung 4 người một chiêu — team chỉ việc dọn dẹp.',
    hero_id: 'krixi',
    tiktok_url: '',
    image_url: '/images/lienquan/khoe-nak.svg',
    like_count: 12,
    created_at: '2026-07-03T10:00:00Z',
  },
  {
    id: 'seed-15',
    display_name: 'YanLateGame',
    caption: 'Yan cấp 12 teamfight — Bang build lao vào là triple kill. End sớm không kịp.',
    hero_id: 'yan',
    tiktok_url: '',
    image_url: '/images/lienquan/khoe-elsu.svg',
    like_count: 33,
    created_at: '2026-07-02T21:00:00Z',
  },
];
