-- Follow-up Security Advisor fix.
-- Previous hardening was added to an already-existing migration, so projects
-- that had already applied it need a new migration to receive these changes.

ALTER TABLE IF EXISTS public."AdminAuditLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."AppSetting" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Bookmark" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Category" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Comment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."CommentDislike" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."CommentLike" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."ContentReport" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Conversation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."DirectMessage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."EmailVerification" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."IpBlockEntry" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."LifeGuide" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."NewsIngestRun" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."NewsSourceConfig" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Notification" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."PartnerBanner" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."PartnerEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."PartnerStore" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Post" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."PostAttachment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."PostLike" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."SearchQueryStat" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."StorageSnapshot" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."User" ENABLE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS public.results ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.quizzes ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.brand_inquiries ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.balance_votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.fortune_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.feature_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.player_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.quiz_completions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.push_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.site_daily_visitors ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.site_visit_exclusions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.lienquan_mastery ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.lienquan_boasts ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.lienquan_boast_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.lienquan_khoe_images ENABLE ROW LEVEL SECURITY;
